name: Build iOS

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: Cache Library
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: |
          Library-
          
    - name: Cache iOS Build
      uses: actions/cache@v3
      with:
        path: build/ios
        key: build-ios-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: |
          build-ios-
          
    - name: Build Unity Project
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: iOS
        buildName: SelfCity
        buildPath: build/ios
        buildMethod: BuildScript.BuildiOS
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: iOS-Build
        path: build/ios 